Repository Hi-PACE/hipace, pull requests merged in 2021-06, with the labels that each got.

#510 Add atomic mass table for Plasmas
  docs/source/run/parameters.rst
  src/particles/PlasmaParticleContainer.cpp
  src/particles/PlasmaParticleContainerInit.cpp
  src/utils/AtomicWeightTable.H
  src/utils/IonizationEnergiesTable.H
  src/utils/atomic_data.txt
  src/utils/write_atomic_data_cpp.py
  src/utils/write_atomic_weight_cpp.py
Labels: component: plasma

#522 CMake 3.20+ and CUDA: Modernized AMReX
  CMakeLists.txt
  cmake/dependencies/AMReX.cmake
Labels: GPU, build

#521 When odd number of cells, no need to average to get slice io
  src/Hipace.cpp
  src/fields/Fields.H
  src/fields/Fields.cpp
Labels: bug, component: diagnostics, component: fields

#524 we dont seem to need Fields::m_F anymore
  src/fields/Fields.H
  src/fields/Fields.cpp
Labels: cleaning, component: fields

#525 remove unused parameters
  src/Hipace.cpp
  src/fields/Fields.H
  src/fields/Fields.cpp
Labels: cleaning

#526 Mesh refinement: Adding IO
  src/Hipace.H
  src/Hipace.cpp
  src/diagnostics/OpenPMDWriter.H
  src/diagnostics/OpenPMDWriter.cpp
  src/fields/Fields.cpp
Labels: component: diagnostics, component: fields

#527 Mesh refinement: multiple Poisson solvers
  src/Hipace.cpp
  src/fields/Fields.H
  src/fields/Fields.cpp
Labels: component: fields

#530 Mesh refinement: first working field solve on level 1
  src/Hipace.H
  src/Hipace.cpp
  src/particles/BeamParticleContainer.H
  src/particles/BeamParticleContainer.cpp
  src/particles/PlasmaParticleContainer.H
  src/particles/PlasmaParticleContainer.cpp
  src/particles/deposition/BeamDepositCurrent.cpp
  src/particles/deposition/PlasmaDepositCurrent.cpp
  src/particles/pusher/BeamParticleAdvance.cpp
  src/particles/pusher/PlasmaParticleAdvance.cpp
  src/utils/GridCurrent.H
  src/utils/GridCurrent.cpp
Labels: component: fields

#531 Mesh refinement: clean loop over levels
  src/Hipace.H
  src/Hipace.cpp
  src/particles/MultiPlasma.H
  src/particles/MultiPlasma.cpp
Labels: cleaning, component: fields

#535 [mini] Fix a few style warnings on AMD
  src/Hipace.H
  src/diagnostics/Diagnostic.H
  src/particles/BeamParticleContainer.H
  src/particles/MultiBeam.H
Labels: cleaning

#533 fix includes for compiling without openPMD
  src/Hipace.H
  src/Hipace.cpp
  src/diagnostics/OpenPMDWriter.H
Labels: bug, build

#540 FFTW: CMakeConfig Support (Windows, OpenMP)
  CMakeLists.txt
  cmake/HiPACEFunctions.cmake
  cmake/dependencies/FFT.cmake
Labels: build, performance

#541 Add OpenMP for FFTW
  cmake/dependencies/FFT.cmake
  src/fields/fft_poisson_solver/fft/WrapDSTW.cpp
Labels: performance

#544 Mesh refinement: fix parallel runs
  src/Hipace.cpp
Labels: Parallelization, bug

#534 New Discrete Sine Transformation
  docs/source/run/parameters.rst
  src/fields/fft_poisson_solver/FFTPoissonSolverDirichlet.cpp
  src/fields/fft_poisson_solver/fft/AnyDST.H
  src/fields/fft_poisson_solver/fft/WrapCuDST.cpp
Labels: GPU, component: fields
