Repository Hi-PACE/hipace, pull requests merged in 2021-09, with the labels that each got.

#586 First HiPACE++ release: version 21.09
  CMakeLists.txt
  cmake/dependencies/AMReX.cmake
  docs/source/conf.py
  license.txt
Labels: documentation

#590 use correct inputs in NotifyFinish
  src/Hipace.cpp
Labels: bug, Parallelization

#580 Output field coarsening
  CMakeLists.txt
  docs/source/run/parameters.rst
  examples/blowout_wake/analysis_coarsening.py
  src/Hipace.cpp
  src/diagnostics/Diagnostic.H
  src/diagnostics/Diagnostic.cpp
  src/fields/Fields.H
  src/fields/Fields.cpp
  tests/output_coarsening.2Rank.sh
Labels: component: fields, component: diagnostics

#582 Only store field comps written to file
  src/Hipace.cpp
  src/diagnostics/Diagnostic.H
  src/diagnostics/Diagnostic.cpp
  src/diagnostics/OpenPMDWriter.cpp
  src/fields/Fields.H
  src/fields/Fields.cpp
Labels: component: fields, component: diagnostics

#592 Initialize m_phys_const earlier
  src/Hipace.H
  src/Hipace.cpp
  src/particles/BeamParticleContainer.cpp
  src/particles/PlasmaParticleContainer.cpp
Labels: cleaning, unit system

#594 only call BeamParticleContainer::ReadParameters() once per Beam
  src/particles/BoxSort.cpp
Labels: component: beam

#583 ROCm & rocFFT
  .github/workflows/hip.yml
  .github/workflows/setup/hip.sh
  docs/source/building/building.rst
  docs/source/building/platforms/spock_olcf.rst
  src/fields/fft_poisson_solver/FFTPoissonSolverDirichlet.cpp
  src/fields/fft_poisson_solver/FFTPoissonSolverPeriodic.cpp
  src/fields/fft_poisson_solver/fft/AnyFFT.H
  src/fields/fft_poisson_solver/fft/CMakeLists.txt
  src/fields/fft_poisson_solver/fft/RocFFTUtils.H
  src/fields/fft_poisson_solver/fft/RocFFTUtils.cpp
  src/fields/fft_poisson_solver/fft/WrapRocDST.cpp
  src/fields/fft_poisson_solver/fft/WrapRocFFT.cpp
Labels: component: fields, GPU, CI

#599 add fix for docutils in requirements
  docs/requirements.txt
Labels: documentation

#598 [mini] fix documentation on how to build the documentation
  docs/source/building/building.rst
Labels: documentation

#600 [mini] call pip with python3 -m
  docs/source/building/building.rst
Labels: documentation

#601 linking openPMD-viewer and VisualPIC in documentation
  docs/source/visualize/visualization.rst
Labels: documentation

#603 CMake: More Robust git STRIP
  cmake/HiPACEFunctions.cmake
Labels: bug, build
