Repository Hi-PACE/hipace, pull requests merged in 2021-05, with the labels that each got.

#486 introduce subheaddings
  docs/source/run/parameters.rst
Labels: documentation

#487 add subcycling for beams
  docs/source/run/parameters.rst
  src/particles/BeamParticleContainer.H
  src/particles/BeamParticleContainer.cpp
  src/particles/pusher/BeamParticleAdvance.cpp
  tests/adaptive_time_step.1Rank.sh
  tests/checksum/benchmarks_json/adaptive_time_step.1Rank.json
Labels: component: beam

#485 change names from WarpX to Hipace++
  tests/checksum/checksumAPI.py
Labels: cleaning

#489 add doc for juwels and maxwell
  docs/source/building/building.rst
  docs/source/building/platforms/booster_jsc.rst
  docs/source/building/platforms/maxwell_desy.rst
Labels: documentation

#490 [mini] add documentation badge
  README.md
Labels: documentation

#491 [mini] Fix typos in readme
  README.md
Labels: documentation

#495 [mini] fix typo in execution command
  docs/source/run/get_started.rst
Labels: documentation

#498 Fix typo in beam from_file
  src/particles/BeamParticleContainerInit.cpp
Labels: cleaning

#500 [mini] remove deprecated comment
  src/Hipace.cpp
Labels: cleaning

#492 add the possibility to have different species of beams
  src/diagnostics/OpenPMDWriter.H
  src/diagnostics/OpenPMDWriter.cpp
  src/particles/BeamParticleContainer.H
  src/particles/BeamParticleContainer.cpp
  src/particles/BeamParticleContainerInit.cpp
  src/particles/deposition/BeamDepositCurrent.cpp
  src/particles/pusher/BeamParticleAdvance.cpp
Labels: component: beam

#493 enable multiple boxes per rank
  docs/source/run/parameters.rst
  src/Hipace.H
  src/Hipace.cpp
Labels: component: fields

#503 remove hardcoded lev calls
  src/Hipace.cpp
Labels: cleaning

#499 enable explicit solver with SI units
  src/Hipace.cpp
  src/particles/deposition/PlasmaDepositCurrentInner.H
Labels: unit system

#501 [mini] clearer naming of direction
  src/Hipace.cpp
Labels: cleaning

#506 [sphinx] add links and logos to package managers
  docs/source/building/brew.svg
  docs/source/building/building.rst
  docs/source/building/spack.svg
Labels: documentation

#507 add proton element for convenience
  src/particles/PlasmaParticleContainer.cpp
Labels: component: plasma

#508 add Adios2 support
  docs/source/run/parameters.rst
  src/diagnostics/OpenPMDWriter.H
  src/diagnostics/OpenPMDWriter.cpp
Labels: component: diagnostics

#513 move Diagnostic class from Fields to Hipace class
  src/Hipace.H
  src/Hipace.cpp
  src/diagnostics/CMakeLists.txt
  src/diagnostics/Diagnostic.H
  src/diagnostics/Diagnostic.cpp
  src/fields/Fields.H
  src/fields/Fields.cpp
Labels: cleaning, component: diagnostics

#515 initialize m_adaptive_density
  src/particles/MultiPlasma.H
  src/utils/AdaptiveTimeStep.cpp
Labels: bug

#516 [mini] Sphinx: fix link in typo
  docs/source/building/building.rst
Labels: documentation

#514 Add beam selection for IO
  docs/source/run/parameters.rst
  src/Hipace.H
  src/Hipace.cpp
  src/diagnostics/Diagnostic.H
  src/diagnostics/Diagnostic.cpp
  src/diagnostics/OpenPMDWriter.H
  src/diagnostics/OpenPMDWriter.cpp
Labels: component: beam, component: diagnostics
