Repository Hi-PACE/hipace, pull requests merged in 2021-11, with the labels that each got.

#610 Docs: Tagfile (Doxygen)
  .github/workflows/source/buildDoxygen
  .gitignore
  docs/Doxyfile
  docs/source/conf.py
Labels: documentation

#612 Abort with useful message if users try to use an input parameters no longer supported
  src/particles/PlasmaParticleContainer.cpp
  src/utils/DeprecatedInput.H
Labels: documentation

#614 Instructions on how to make a new release
  docs/source/contributing/contributing.rst
Labels: documentation

#616 use correct CUDA version on maxwell
  docs/source/building/platforms/maxwell_desy.rst
Labels: bug, documentation, build

#618 control adaptive time step with hipace.dt
  docs/source/run/parameters.rst
  examples/beam_in_vacuum/analysis_adaptive_ts.py
  src/Hipace.cpp
  src/utils/AdaptiveTimeStep.H
  src/utils/AdaptiveTimeStep.cpp
  tests/adaptive_time_step.1Rank.sh
Labels: documentation

#619 deprecate hipace.do_adaptive_time_step
  src/utils/AdaptiveTimeStep.cpp
Labels: cleaning

#622 Fix a data type problem with openpmd metadata writer
  src/diagnostics/OpenPMDWriter.cpp
Labels: bug, build, component: diagnostics

#621 MPI send buffer for the physical time
  src/Hipace.H
  src/Hipace.cpp
  src/particles/BeamParticleContainer.H
  src/particles/BeamParticleContainer.cpp
  src/particles/BeamParticleContainerInit.cpp
  src/particles/MultiBeam.H
  src/particles/MultiBeam.cpp
Labels: bug, Parallelization, pipeline

#620 Add image to doc page
  docs/source/image.png
  docs/source/index.rst
Labels: documentation
