Repository Hi-PACE/hipace, pull requests merged in 2022-07, with the labels that each got.

#766 [mini] remove unused rp in plasma init
  src/particles/PlasmaParticleContainerInit.cpp
Labels: cleaning, build

#771 Fix adaptive time step
  src/Hipace.cpp
  src/utils/AdaptiveTimeStep.H
  src/utils/AdaptiveTimeStep.cpp
Labels: bug, component: beam

#769 Clean up in-situ beam diagnostics
  docs/source/run/parameters.rst
  src/Hipace.cpp
  src/particles/BeamParticleContainer.H
  src/particles/BeamParticleContainer.cpp
  src/particles/MultiBeam.H
  src/particles/MultiBeam.cpp
  src/utils/InsituUtil.H
  src/utils/Parser.H
  tools/read_insitu_diagnostics.py
Labels: component: beam, cleaning, component: diagnostics
