Repository Hi-PACE/hipace, pull requests merged in 2022-02, with the labels that each got.

#656 More detailed performance diagnostics of AdvancePlasmaParticles
  src/particles/pusher/PlasmaParticleAdvance.cpp
Labels: performance

#658 move unused variable in serial to MPI code
  src/Hipace.cpp
Labels: cleaning, build

#649 Improve Diagnostics
  docs/source/run/parameters.rst
  src/Hipace.cpp
  src/diagnostics/Diagnostic.H
  src/diagnostics/Diagnostic.cpp
  src/diagnostics/OpenPMDWriter.H
  src/diagnostics/OpenPMDWriter.cpp
  src/fields/Fields.H
  src/fields/Fields.cpp
Labels: component: diagnostics

#659 add safeguard for bugged cuda version, and print cuda version
  src/Hipace.cpp
  src/fields/fft_poisson_solver/fft/WrapCuDST.cpp
  src/fields/fft_poisson_solver/fft/WrapCuFFT.cpp
Labels: bug, GPU

#662 choose default output path by backend
  src/diagnostics/OpenPMDWriter.H
  src/diagnostics/OpenPMDWriter.cpp
Labels: component: diagnostics

#661 update fixed ppc beams and a few other things in documentation
  docs/source/run/parameters.rst
Labels: documentation

#664 fix typo in table in documentation
  docs/source/run/parameters.rst
Labels: documentation

#657 Add serial compilation to CI
  .github/workflows/linux.yml
  .github/workflows/setup/ubuntu.sh
  tests/checksum/benchmarks_json/beam_in_vacuum.SI.Serial.json
  tests/checksum/benchmarks_json/beam_in_vacuum.normalized.Serial.json
  tests/checksum/benchmarks_json/blowout_wake.Serial.json
  tests/checksum/reset_all_benchmarks.sh
Labels: build, CI

#670 [mini] update doc on Spock
  docs/source/building/platforms/spock_olcf.rst
Labels: documentation, GPU, build

#673 Normalize explicit solver with nominal density rather than max density
  docs/source/run/parameters.rst
  src/Hipace.cpp
  src/particles/MultiPlasma.H
  src/particles/MultiPlasma.cpp
Labels: bug, documentation, component: plasma, unit system

#669 Fix AMD small dst
  src/fields/fft_poisson_solver/fft/AnyDST.H
  src/fields/fft_poisson_solver/fft/WrapRocDST.cpp
Labels: GPU

#681 Use AMReX release 22.01 by default instead of latest development
  cmake/dependencies/AMReX.cmake
Labels: bug, build

#682 clean documentation
  docs/source/building/building.rst
  docs/source/index.rst
  docs/source/run/run.rst
Labels: documentation, cleaning
