Repository Hi-PACE/hipace, pull requests merged in 2022-12, with the labels that each got.

#831 Add derivative shape factors
  docs/source/run/parameters.rst
  src/Hipace.H
  src/Hipace.cpp
  src/particles/deposition/ExplicitDeposition.cpp
  src/particles/deposition/PlasmaDepositCurrent.cpp
  src/particles/particles_utils/ShapeFactors.H
Labels: component: plasma, GPU, performance

#832 Udate version number
  CMakeLists.txt
  docs/source/conf.py
  license.txt
Labels: documentation

#833 fix NVCC 11.5+ compile issue
  src/particles/deposition/ExplicitDeposition.cpp
Labels: bug, build

#834 update CUDA CI to 11.8
  .github/workflows/cuda.yml
  .github/workflows/setup/nvcc11.sh
Labels: build, CI

#835 Mesh Refinement with Explicit Solver
  src/Hipace.H
  src/Hipace.cpp
  src/fields/Fields.H
  src/fields/Fields.cpp
  src/laser/MultiLaser.cpp
  src/mg_solver/HpMultiGrid.H
  src/mg_solver/HpMultiGrid.cpp
  src/salame/Salame.cpp
Labels: component: fields, mesh refinement

#840 [mini] Clearly state in the doc that HiPACE++ is 3D
  docs/source/index.rst
Labels: documentation

#841 Remove numprocs_x/y in all inputs, useless and confusing
  examples/beam_in_vacuum/inputs_SI
  examples/beam_in_vacuum/inputs_normalized
  examples/beam_in_vacuum/inputs_normalized_transverse
  examples/blowout_wake/inputs_SI
  examples/blowout_wake/inputs_ionization_SI
  examples/blowout_wake/inputs_normalized
  examples/gaussian_weight/inputs_SI
  examples/gaussian_weight/inputs_normalized
  examples/laser/inputs_SI
  examples/linear_wake/inputs_SI
  examples/linear_wake/inputs_ion_motion_SI
  examples/linear_wake/inputs_normalized
Labels: documentation, cleaning, Parallelization
