Repository Hi-PACE/hipace, pull requests merged in 2022-01, with the labels that each got.

#635 Doxygen: include `static` functions
  docs/Doxyfile
Labels: documentation

#636 avoid amrex ref_ratio which does not exist without MR
  src/Hipace.H
  src/Hipace.cpp
  src/particles/MultiBeam.H
  src/particles/MultiBeam.cpp
  src/particles/SliceSort.H
  src/particles/SliceSort.cpp
Labels: bug

#640 Pass the number of ghost cells to amrex::MultiFab::setVal, etc.
  src/Hipace.cpp
  src/fields/Fields.H
  src/fields/Fields.cpp
  tests/checksum/benchmarks_json/blowout_wake_explicit.2Rank.json
Labels: bug

#645 CI: HIP Latest
  .github/workflows/hip.yml
  .github/workflows/setup/hip.sh
Labels: GPU, CI

#642 also allow random seed on GPU
  src/Hipace.cpp
Labels: GPU

#643 Simplify conversion between positions and indices
  src/Hipace.H
  src/Hipace.cpp
  src/fields/Fields.H
  src/particles/MultiBeam.H
  src/particles/MultiBeam.cpp
  src/particles/PlasmaParticleContainer.cpp
  src/particles/deposition/BeamDepositCurrent.H
  src/particles/deposition/BeamDepositCurrent.cpp
  src/particles/deposition/BeamDepositCurrentInner.H
  src/particles/deposition/PlasmaDepositCurrent.cpp
  src/particles/deposition/PlasmaDepositCurrentInner.H
  src/particles/pusher/BeamParticleAdvance.cpp
  src/particles/pusher/FieldGather.H
  src/particles/pusher/PlasmaParticleAdvance.cpp
Labels: cleaning

#646 GPU Builds: Disable RDC
  cmake/dependencies/AMReX.cmake
Labels: GPU, performance, build

#652 Fix: CUDA C++17 Builds (ParticleBins)
  src/particles/SliceSort.cpp
  src/particles/TileSort.cpp
Labels: bug, GPU

#653 update cmake in maxwell doc
  docs/source/building/platforms/maxwell_desy.rst
Labels: documentation, build

#654 ignore or remove unused parameters
  src/fields/fft_poisson_solver/fft/WrapRocDST.cpp
  src/particles/ShapeFactors.H
Labels: cleaning

#651 CI: CUDA
  .github/workflows/cuda.yml
  .github/workflows/linux.yml
  .github/workflows/setup/nvcc11.sh
  .github/workflows/setup/nvhpc.sh
Labels: GPU, CI

#623 Clean up field indexing to allow for better handling of boundary
  src/fields/Fields.H
  src/fields/Fields.cpp
  src/fields/fft_poisson_solver/FFTPoissonSolverDirichlet.cpp
  src/fields/fft_poisson_solver/FFTPoissonSolverPeriodic.cpp
  src/fields/fft_poisson_solver/fft/WrapCuDST.cpp
  src/fields/fft_poisson_solver/fft/WrapRocDST.cpp
  src/particles/deposition/PlasmaDepositCurrentInner.H
Labels: component: fields, cleaning

#650 C++17, CMake 3.18+
  .github/workflows/linux.yml
  .github/workflows/setup/ubuntu_clang.sh
  CMakeLists.txt
  cmake/HiPACEFunctions.cmake
  cmake/dependencies/openPMD.cmake
  docs/source/building/building.rst
Labels: build
