Repository Hi-PACE/hipace, pull requests merged in 2022-03, with the labels that each got.

#685 Restore default behavior: use latest amrex development
  .github/workflows/linux.yml
  cmake/dependencies/AMReX.cmake
Labels: bug, build, CI

#674 [mini] remove a few spurious semi-colons
  src/particles/MultiPlasma.H
  src/particles/PlasmaParticleContainer.H
Labels: cleaning, build

#677 Fix typo in sort bin type
  src/particles/deposition/PlasmaDepositCurrentInner.H
Labels: bug, component: plasma, component: beam

#687 Pass Bins as const ref whenever possible
  src/Hipace.H
  src/Hipace.cpp
  src/particles/MultiBeam.H
  src/particles/MultiBeam.cpp
  src/particles/deposition/BeamDepositCurrent.H
  src/particles/deposition/BeamDepositCurrent.cpp
  src/particles/deposition/BeamDepositCurrentInner.H
  src/particles/pusher/BeamParticleAdvance.H
  src/particles/pusher/BeamParticleAdvance.cpp
Labels: bug, component: beam, GPU

#693 [mini] Add a few consts
  src/particles/deposition/PlasmaDepositCurrent.H
  src/particles/deposition/PlasmaDepositCurrent.cpp
  src/particles/deposition/PlasmaDepositCurrentInner.H
Labels: component: plasma

#701 fix indexing error causing crash in parallel runs
  src/fields/fft_poisson_solver/fft/WrapCuDST.cpp
Labels: bug

#702 fix debug linking issue causing crash in Parser
  src/utils/CMakeLists.txt
  src/utils/Parser.H
  src/utils/Parser.cpp
Labels: bug

#691 CI: ccache
  .github/workflows/cuda.yml
  .github/workflows/hip.yml
  .github/workflows/linux.yml
  .github/workflows/setup/hip.sh
  .github/workflows/setup/macos.sh
  .github/workflows/setup/macos_omp.sh
  .github/workflows/setup/nvcc11.sh
  .github/workflows/setup/nvhpc.sh
  .github/workflows/setup/ubuntu.sh
  .github/workflows/setup/ubuntu_clang.sh
  .github/workflows/setup/ubuntu_ompi.sh
  .github/workflows/setup/ubuntu_ompi_cuda.sh
Labels: CI

#700 Version Define File
  CMakeLists.txt
  src/CMakeLists.txt
  src/Hipace.cpp
  src/HipaceVersion.H.in
  src/HipaceVersion.cpp
Labels: bug, build, CI

#699 hpmg::MultiGrid
  src/CMakeLists.txt
  src/Hipace.H
  src/Hipace.cpp
  src/mg_solver/CMakeLists.txt
  src/mg_solver/HpMultiGrid.H
  src/mg_solver/HpMultiGrid.cpp
Labels: performance

#709 README: Add Source & Paper Archives
  README.md
Labels: documentation

#705 [mini] Do not compile AMReX linear solvers by default
  cmake/dependencies/AMReX.cmake
  docs/source/building/building.rst
Labels: build

#706 [mini] Add a few double quotes for doc formatting
  docs/source/run/parameters.rst
Labels: documentation, cleaning

#708 [mini] Silent warning on deprecated np.int
  examples/linear_wake/analysis.py
Labels: cleaning, CI

#707 Redefine particle psi as normalized psi+1
  src/particles/PlasmaParticleContainer.H
  src/particles/PlasmaParticleContainer.cpp
  src/particles/PlasmaParticleContainerInit.cpp
  src/particles/deposition/PlasmaDepositCurrentInner.H
  src/particles/pusher/PlasmaParticleAdvance.cpp
  src/particles/pusher/UpdateForceTerms.H
Labels: component: plasma, cleaning, performance, unit system

#676 Implement binary Coulomb collisions between plasma species
  CMakeLists.txt
  docs/source/run/parameters.rst
  src/Hipace.cpp
  src/particles/CMakeLists.txt
  src/particles/ComputeTemperature.H
  src/particles/CoulombCollision.H
  src/particles/CoulombCollision.cpp
  src/particles/ElasticCollisionPerez.H
  src/particles/MultiPlasma.H
  src/particles/MultiPlasma.cpp
  src/particles/PlasmaParticleContainer.H
  src/particles/ShuffleFisherYates.H
  src/particles/TileSort.H
  src/particles/TileSort.cpp
  src/particles/UpdateMomentumPerez.H
  src/utils/Constants.H
  tests/checksum/benchmarks_json/collisions.SI.1Rank.json
  tests/checksum/reset_all_benchmarks.sh
  tests/collisions.SI.1Rank.sh
Labels: documentation, component: plasma

#641 Laser envelope: static laser
  CMakeLists.txt
  docs/source/run/parameters.rst
  src/CMakeLists.txt
  src/Hipace.H
  src/Hipace.cpp
  src/laser/CMakeLists.txt
  src/laser/Laser.H
  src/laser/Laser.cpp
  src/particles/MultiPlasma.H
  src/particles/MultiPlasma.cpp
  src/particles/deposition/PlasmaDepositCurrent.H
  src/particles/deposition/PlasmaDepositCurrent.cpp
  src/particles/deposition/PlasmaDepositCurrentInner.H
  src/particles/pusher/FieldGather.H
  src/particles/pusher/PlasmaParticleAdvance.H
  src/particles/pusher/PlasmaParticleAdvance.cpp
  src/particles/pusher/UpdateForceTerms.H
  tests/checksum/benchmarks_json/laser_blowout_wake_explicit.1Rank.json
  tests/checksum/benchmarks_json/laser_blowout_wake_explicit.SI.1Rank.json
  tests/checksum/reset_all_benchmarks.sh
  tests/laser_blowout_wake_explicit.1Rank.sh
  tests/laser_blowout_wake_explicit.SI.1Rank.sh
Labels: component: laser envelope

#720 [mini] constify field access
  src/Hipace.cpp
  src/fields/Fields.H
  src/particles/MultiBeam.H
  src/particles/MultiBeam.cpp
  src/particles/MultiPlasma.H
  src/particles/MultiPlasma.cpp
  src/particles/PlasmaParticleContainer.H
  src/particles/PlasmaParticleContainer.cpp
  src/particles/pusher/BeamParticleAdvance.H
  src/particles/pusher/BeamParticleAdvance.cpp
  src/particles/pusher/PlasmaParticleAdvance.H
  src/particles/pusher/PlasmaParticleAdvance.cpp
Labels: cleaning

#723 allow for offset fixed ppc beam
  src/particles/BeamParticleContainer.H
  src/particles/BeamParticleContainer.cpp
  src/particles/BeamParticleContainerInit.cpp
  src/particles/pusher/GetAndSetPosition.H
Labels: component: beam

#725 Change checksum backend to h5py to improve CI performance
  tests/checksum/backend/openpmd_backend.py
Labels: bug, CI
