Repository Hi-PACE/hipace, pull requests merged in 2022-11, with the labels that each got.

#807 Avoid spurious copies to/from GPU in laser MPI communication pattern
  src/Hipace.cpp
  src/laser/Laser.H
Labels: cleaning, GPU, performance, Parallelization, component: laser envelope

#799 Fix memory access in BeamBins
  src/Hipace.cpp
  src/particles/BeamParticleContainer.H
  src/particles/BeamParticleContainer.cpp
  src/particles/MultiBeam.cpp
  src/particles/SliceSort.H
  src/particles/deposition/BeamDepositCurrentInner.H
  src/particles/pusher/BeamParticleAdvance.cpp
Labels: GPU, performance

#800 Fix memory access in Fields::Copy
  src/fields/Fields.H
  src/fields/Fields.cpp
Labels: GPU, performance

#809 Option to use a more accurate discretisation for laser envelope
  docs/source/run/parameters.rst
  src/laser/Laser.H
  src/laser/Laser.cpp
  tests/laser_evolution.SI.2Rank.sh
Labels: component: laser envelope

#805 Directly deposit source terms for the explicit solver
  src/Hipace.cpp
  src/fields/Fields.H
  src/fields/Fields.cpp
  src/laser/Laser.cpp
  src/particles/MultiBeam.H
  src/particles/MultiBeam.cpp
  src/particles/MultiPlasma.H
  src/particles/MultiPlasma.cpp
  src/particles/PlasmaParticleContainer.cpp
  src/particles/deposition/BeamDepositCurrent.H
  src/particles/deposition/BeamDepositCurrent.cpp
  src/particles/deposition/CMakeLists.txt
  src/particles/deposition/ExplicitDeposition.H
  src/particles/deposition/ExplicitDeposition.cpp
  src/particles/deposition/PlasmaDepositCurrent.H
  src/particles/deposition/PlasmaDepositCurrent.cpp
  src/particles/deposition/PlasmaDepositCurrentInner.H
  src/particles/pusher/FieldGather.H
  src/particles/pusher/UpdateForceTerms.H
  src/utils/GPUUtil.H
  tests/blowout_wake_explicit.2Rank.sh
  tests/checksum/benchmarks_json/blowout_wake_explicit.2Rank.json
  tests/checksum/benchmarks_json/ion_motion.SI.1Rank.json
  tests/checksum/benchmarks_json/laser_blowout_wake_explicit.1Rank.json
  tests/checksum/benchmarks_json/laser_blowout_wake_explicit.SI.1Rank.json
  tests/checksum/benchmarks_json/laser_evolution.SI.2Rank.json
  tests/ion_motion.SI.1Rank.sh
  tests/laser_blowout_wake_explicit.1Rank.sh
  tests/laser_blowout_wake_explicit.SI.1Rank.sh
Labels: bug, component: plasma, component: fields, cleaning

#810 add more subfolders to src/particles/
  src/Hipace.H
  src/Hipace.cpp
  src/diagnostics/OpenPMDWriter.H
  src/fields/Fields.cpp
  src/particles/CMakeLists.txt
  src/particles/beam/BeamParticleContainer.H
  src/particles/beam/BeamParticleContainer.cpp
  src/particles/beam/BeamParticleContainerInit.cpp
  src/particles/beam/CMakeLists.txt
  src/particles/beam/MultiBeam.H
  src/particles/beam/MultiBeam.cpp
  src/particles/collisions/CMakeLists.txt
  src/particles/collisions/ComputeTemperature.H
  src/particles/collisions/CoulombCollision.H
  src/particles/collisions/CoulombCollision.cpp
  src/particles/collisions/ElasticCollisionPerez.H
  src/particles/collisions/ShuffleFisherYates.H
  src/particles/collisions/UpdateMomentumPerez.H
  src/particles/deposition/BeamDepositCurrent.H
  src/particles/deposition/BeamDepositCurrent.cpp
  src/particles/deposition/BeamDepositCurrentInner.H
  src/particles/deposition/ExplicitDeposition.H
  src/particles/deposition/ExplicitDeposition.cpp
  src/particles/deposition/PlasmaDepositCurrent.H
  src/particles/deposition/PlasmaDepositCurrent.cpp
  src/particles/deposition/PlasmaDepositCurrentInner.H
  src/particles/particles_utils/FieldGather.H
  src/particles/particles_utils/ParticleUtil.H
  src/particles/particles_utils/ShapeFactors.H
  src/particles/plasma/CMakeLists.txt
  src/particles/plasma/MultiPlasma.H
  src/particles/plasma/MultiPlasma.cpp
  src/particles/plasma/PlasmaParticleContainer.H
  src/particles/plasma/PlasmaParticleContainer.cpp
  src/particles/plasma/PlasmaParticleContainerInit.cpp
  src/particles/profiles/GetInitialMomentum.H
  src/particles/pusher/BeamParticleAdvance.H
  src/particles/pusher/BeamParticleAdvance.cpp
  src/particles/pusher/ExternalFields.H
  src/particles/pusher/GetAndSetPosition.H
  src/particles/pusher/PlasmaParticleAdvance.H
  src/particles/pusher/PlasmaParticleAdvance.cpp
  src/particles/pusher/PushPlasmaParticles.H
  src/particles/sorting/BoxSort.H
  src/particles/sorting/BoxSort.cpp
  src/particles/sorting/CMakeLists.txt
  src/particles/sorting/SliceSort.H
  src/particles/sorting/SliceSort.cpp
  src/particles/sorting/TileSort.H
  src/particles/sorting/TileSort.cpp
  src/utils/AdaptiveTimeStep.H
Labels: component: plasma, component: beam, cleaning

#812 Update version number before release
  CMakeLists.txt
  docs/source/conf.py
  license.txt
Labels: documentation

#813 Fix invalid CUDA device function error in HPMG
  src/mg_solver/HpMultiGrid.H
  src/mg_solver/HpMultiGrid.cpp
Labels: bug, GPU

#816 [mini] print number of iterations only for PC solver
  src/Hipace.cpp
Labels: cleaning

#814 Automatic Beam loading using a near direct SALAME algorithm
  docs/source/run/parameters.rst
  src/CMakeLists.txt
  src/Hipace.H
  src/Hipace.cpp
  src/fields/Fields.H
  src/fields/Fields.cpp
  src/particles/beam/BeamParticleContainer.H
  src/particles/beam/BeamParticleContainer.cpp
  src/particles/beam/BeamParticleContainerInit.cpp
  src/particles/beam/MultiBeam.H
  src/particles/beam/MultiBeam.cpp
  src/particles/deposition/BeamDepositCurrent.cpp
  src/particles/deposition/BeamDepositCurrentInner.H
  src/particles/deposition/PlasmaDepositCurrent.cpp
  src/particles/plasma/MultiPlasma.H
  src/salame/CMakeLists.txt
  src/salame/Salame.H
  src/salame/Salame.cpp
Labels: component: beam

#817 add documentation for Perlmutter
  docs/source/building/building.rst
  docs/source/building/platforms/perlmutter_nersc.rst
Labels: documentation

#818 Fix errors in I/O
  src/Hipace.cpp
  src/diagnostics/OpenPMDWriter.H
  src/diagnostics/OpenPMDWriter.cpp
Labels: bug, component: diagnostics

#821 [mini] option to not use the phase for laser envelope advance
  docs/source/run/parameters.rst
  src/laser/Laser.H
  src/laser/Laser.cpp
Labels: component: laser envelope

#819 clean up deposition using ParallelFor with compile time optimizations
  src/laser/Laser.H
  src/laser/Laser.cpp
  src/particles/deposition/BeamDepositCurrent.cpp
  src/particles/deposition/BeamDepositCurrentInner.H
  src/particles/deposition/PlasmaDepositCurrent.cpp
  src/particles/deposition/PlasmaDepositCurrentInner.H
  src/particles/particles_utils/FieldGather.H
  src/particles/plasma/PlasmaParticleContainer.cpp
  src/particles/pusher/BeamParticleAdvance.cpp
  src/particles/pusher/PlasmaParticleAdvance.cpp
  src/salame/Salame.cpp
  src/utils/GPUUtil.H
Labels: bug, cleaning

#825 Fix Juwels compile issue
  src/particles/deposition/PlasmaDepositCurrent.cpp
Labels: bug, GPU, build

#826 [mini] Fix docstring of laser gather function
  src/particles/particles_utils/FieldGather.H
Labels: documentation

#823 Enable multiple laser pulses
  docs/source/run/parameters.rst
  examples/beam_in_vacuum/inputs_SI
  examples/beam_in_vacuum/inputs_normalized
  examples/beam_in_vacuum/inputs_normalized_transverse
  examples/blowout_wake/inputs_SI
  examples/blowout_wake/inputs_ionization_SI
  examples/blowout_wake/inputs_normalized
  examples/gaussian_weight/inputs_SI
  examples/gaussian_weight/inputs_normalized
  examples/get_started/inputs_normalized
  examples/laser/inputs_SI
  examples/linear_wake/inputs_SI
  examples/linear_wake/inputs_ion_motion_SI
  examples/linear_wake/inputs_normalized
  src/Hipace.H
  src/Hipace.cpp
  src/fields/Fields.H
  src/fields/Fields.cpp
  src/laser/CMakeLists.txt
  src/laser/Laser.H
  src/laser/Laser.cpp
  src/laser/MultiLaser.H
  src/laser/MultiLaser.cpp
  src/particles/deposition/ExplicitDeposition.H
  src/particles/deposition/ExplicitDeposition.cpp
  src/particles/deposition/PlasmaDepositCurrent.H
  src/particles/deposition/PlasmaDepositCurrent.cpp
  src/particles/plasma/MultiPlasma.H
  src/particles/plasma/MultiPlasma.cpp
  src/particles/pusher/PlasmaParticleAdvance.H
  src/particles/pusher/PlasmaParticleAdvance.cpp
  src/salame/Salame.cpp
  tests/laser_blowout_wake_explicit.1Rank.sh
  tests/laser_blowout_wake_explicit.SI.1Rank.sh
  tests/laser_evolution.SI.2Rank.sh
Labels: documentation, GPU, component: laser envelope

#827 reset laser slices before DepositNeutralizingBackground
  src/Hipace.cpp
Labels: bug, component: laser envelope

#830 [mini] Enable laser transverse offset
  src/laser/Laser.cpp
  src/laser/MultiLaser.cpp
Labels: component: laser envelope
