Repository Hi-PACE/hipace, pull requests merged in 2022-06, with the labels that each got.

#740 Implementation of max_time
  docs/source/run/parameters.rst
  src/Hipace.H
  src/Hipace.cpp
Labels: Parallelization

#752 Fix debug crash from empty multifab
  src/Hipace.cpp
  src/fields/Fields.H
  src/fields/Fields.cpp
Labels: bug

#754 [mini] gpu synchronize after beam particle sort per slice
  src/particles/MultiBeam.cpp
Labels: bug, GPU

#750 [mini] improve documentation on field_data
  docs/source/run/parameters.rst
Labels: documentation

#751 [mini] update link to paper
  README.md
Labels: documentation, cleaning

#756 fix zero weight issue in insitu diagnostics
  src/particles/BeamParticleContainer.cpp
Labels: bug, component: diagnostics

#760 Generalize beam tilt to any function of z
  docs/source/run/parameters.rst
  examples/beam_in_vacuum/inputs_normalized_transverse
  examples/linear_wake/inputs_ion_motion_SI
  src/particles/BeamParticleContainer.H
  src/particles/BeamParticleContainer.cpp
  src/particles/BeamParticleContainerInit.cpp
  tests/gaussian_weight.1Rank.sh
Labels: component: beam

#761 use GetUStd per plasma instead of on MultiPlasma in explicit solver
  src/Hipace.cpp
  src/particles/MultiPlasma.H
  src/particles/MultiPlasma.cpp
Labels: component: plasma

#762 Increase MPI message size limit for beam particles
  src/Hipace.cpp
Labels: Parallelization

#765 add minimal plasma density, deprecate parabolic curvature
  docs/source/run/parameters.rst
  src/particles/PlasmaParticleContainer.H
  src/particles/PlasmaParticleContainer.cpp
  src/particles/PlasmaParticleContainerInit.cpp
  src/utils/DeprecatedInput.H
Labels: component: plasma, cleaning

#764 enable zmin, zmax for fixed weight beam
  docs/source/run/parameters.rst
  src/particles/BeamParticleContainer.H
  src/particles/BeamParticleContainer.cpp
  src/particles/BeamParticleContainerInit.cpp
  src/particles/BoxSort.cpp
Labels: component: beam
