Repository Hi-PACE/hipace, pull requests merged in 2023-09, with the labels that each got.

#1013 push beam particles on correct slice when subcycling
  src/Hipace.cpp
  src/particles/beam/BeamParticleContainer.H
  src/particles/beam/BeamParticleContainer.cpp
  src/particles/beam/BeamParticleContainerInit.cpp
  src/particles/beam/MultiBeam.H
  src/particles/beam/MultiBeam.cpp
  src/particles/pusher/BeamParticleAdvance.H
  src/particles/pusher/BeamParticleAdvance.cpp
  tests/checksum/benchmarks_json/production.SI.2Rank_pwfa.json
Labels: component: beam

#1017 [mini] update LUMI docs
  docs/source/building/platforms/lumi_csc.rst
Labels: documentation

#1018 Plasma initialization for MR
  docs/source/run/parameters.rst
  src/particles/particles_utils/ParticleUtil.H
  src/particles/plasma/PlasmaParticleContainer.H
  src/particles/plasma/PlasmaParticleContainer.cpp
  src/particles/plasma/PlasmaParticleContainerInit.cpp
Labels: component: plasma, mesh refinement

#1019 Workaround std::gcd and std::lcm constexpr issue
  src/utils/MultiBuffer.H
Labels: bug, build

#1015 Faster multigrid solve using shared memory
  src/mg_solver/HpMultiGrid.cpp
Labels: GPU, performance
