Repository Hi-PACE/hipace, pull requests merged in 2023-05, with the labels that each got.

#926 Add time to CI ccache restore key
  .github/workflows/cuda.yml
  .github/workflows/hip.yml
  .github/workflows/linux.yml
  .github/workflows/macos.yml
  .github/workflows/windows.yml
Labels: performance, CI

#929 Remove NumPy from brew cache
  .github/workflows/macos.yml
Labels: bug

#924 Dynamic particle level
  docs/source/run/parameters.rst
  src/Hipace.cpp
  src/particles/beam/BeamParticleContainer.H
  src/particles/beam/BeamParticleContainer.cpp
  src/particles/beam/BeamParticleContainerInit.cpp
  src/particles/beam/MultiBeam.H
  src/particles/beam/MultiBeam.cpp
  src/particles/collisions/CoulombCollision.cpp
  src/particles/deposition/BeamDepositCurrent.cpp
  src/particles/deposition/ExplicitDeposition.H
  src/particles/deposition/ExplicitDeposition.cpp
  src/particles/deposition/PlasmaDepositCurrent.H
  src/particles/deposition/PlasmaDepositCurrent.cpp
  src/particles/plasma/MultiPlasma.H
  src/particles/plasma/MultiPlasma.cpp
  src/particles/plasma/PlasmaParticleContainer.H
  src/particles/plasma/PlasmaParticleContainer.cpp
  src/particles/plasma/PlasmaParticleContainerInit.cpp
  src/particles/pusher/BeamParticleAdvance.cpp
  src/particles/pusher/PlasmaParticleAdvance.H
  src/particles/pusher/PlasmaParticleAdvance.cpp
  src/particles/sorting/TileSort.H
  src/particles/sorting/TileSort.cpp
  src/salame/Salame.cpp
  src/utils/GridCurrent.H
  src/utils/GridCurrent.cpp
Labels: mesh refinement

#927 Fully initialize plasma every timestep
  src/Hipace.cpp
  src/particles/plasma/MultiPlasma.H
  src/particles/plasma/MultiPlasma.cpp
  src/particles/plasma/PlasmaParticleContainer.H
  src/particles/plasma/PlasmaParticleContainer.cpp
  src/particles/plasma/PlasmaParticleContainerInit.cpp
  src/particles/pusher/PlasmaParticleAdvance.H
  src/particles/pusher/PlasmaParticleAdvance.cpp
  tests/checksum/benchmarks_json/collisions.SI.1Rank.json
  tests/checksum/benchmarks_json/ionization.2Rank.json
Labels: bug, component: plasma

#935 add config file for readthedocs
  .readthedocs.yml
Labels: documentation

#937 macOS CI add HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK
  .github/workflows/macos.yml
Labels: performance, CI

#932 fix a bunch of issues in the documentation
  docs/source/building/building.rst
  docs/source/building/platforms/perlmutter_nersc.rst
  docs/source/run/parameters.rst
Labels: documentation, cleaning

#936 Interpolate jx_beam and jy_beam to level 1
  src/Hipace.cpp
  src/fields/Fields.H
  src/fields/Fields.cpp
Labels: component: fields, mesh refinement

#939 update Perlmutter documentation
  docs/source/building/platforms/perlmutter_nersc.rst
Labels: documentation

#940 Replace rho field with rho - jz/c
  docs/source/run/parameters.rst
  examples/beam_in_vacuum/analysis_2ranks.py
  examples/beam_in_vacuum/analysis_grid_current.py
  src/Hipace.H
  src/Hipace.cpp
  src/diagnostics/Diagnostic.H
  src/diagnostics/Diagnostic.cpp
  src/fields/Fields.H
  src/fields/Fields.cpp
  src/particles/beam/MultiBeam.H
  src/particles/beam/MultiBeam.cpp
  src/particles/deposition/BeamDepositCurrent.H
  src/particles/deposition/BeamDepositCurrent.cpp
  src/particles/deposition/PlasmaDepositCurrent.H
  src/particles/deposition/PlasmaDepositCurrent.cpp
  src/particles/plasma/MultiPlasma.H
  src/particles/plasma/MultiPlasma.cpp
  src/salame/Salame.cpp
  tests/beam_in_vacuum.SI.1Rank.sh
  tests/beam_in_vacuum.SI.Serial.sh
  tests/beam_in_vacuum.normalized.1Rank.sh
  tests/beam_in_vacuum.normalized.2Rank.sh
  tests/beam_in_vacuum.normalized.Serial.sh
  tests/beam_in_vacuum_open_boundary.normalized.1Rank.sh
  tests/checksum/benchmark.py
  tests/checksum/benchmarks_json/adaptive_time_step.1Rank.json
  tests/checksum/benchmarks_json/beam_evolution.1Rank.json
  tests/checksum/benchmarks_json/beam_in_vacuum.SI.1Rank.json
  tests/checksum/benchmarks_json/beam_in_vacuum.SI.Serial.json
  tests/checksum/benchmarks_json/beam_in_vacuum.normalized.1Rank.json
  tests/checksum/benchmarks_json/beam_in_vacuum.normalized.Serial.json
  tests/checksum/benchmarks_json/beam_in_vacuum_open_boundary.normalized.1Rank.json
  tests/checksum/benchmarks_json/blowout_wake.2Rank.json
  tests/checksum/benchmarks_json/blowout_wake.Serial.json
  tests/checksum/benchmarks_json/blowout_wake_explicit.2Rank.json
  tests/checksum/benchmarks_json/collisions.SI.1Rank.json
  tests/checksum/benchmarks_json/gaussian_linear_wake.SI.1Rank.json
  tests/checksum/benchmarks_json/gaussian_linear_wake.normalized.1Rank.json
  tests/checksum/benchmarks_json/gaussian_weight.1Rank.json
  tests/checksum/benchmarks_json/grid_current.1Rank.json
  tests/checksum/benchmarks_json/ion_motion.SI.1Rank.json
  tests/checksum/benchmarks_json/ionization.2Rank.json
  tests/checksum/benchmarks_json/laser_blowout_wake_explicit.1Rank.json
  tests/checksum/benchmarks_json/laser_blowout_wake_explicit.SI.1Rank.json
  tests/checksum/benchmarks_json/laser_evolution.SI.2Rank.json
  tests/checksum/benchmarks_json/linear_wake.SI.1Rank.json
  tests/checksum/benchmarks_json/linear_wake.normalized.1Rank.json
  tests/checksum/benchmarks_json/production.SI.2Rank_lwfa.json
  tests/checksum/benchmarks_json/production.SI.2Rank_pwfa.json
  tests/checksum/benchmarks_json/reset.2Rank.json
  tests/gaussian_linear_wake.SI.1Rank.sh
  tests/gaussian_linear_wake.normalized.1Rank.sh
  tests/linear_wake.SI.1Rank.sh
  tests/linear_wake.normalized.1Rank.sh
Labels: bug, component: plasma, component: fields, performance

#930 CI: apt retry and new Easyinstall link
  .github/workflows/setup/hip.sh
  .github/workflows/setup/nvcc11.sh
  .github/workflows/setup/nvhpc.sh
  .github/workflows/setup/ubuntu.sh
  .github/workflows/setup/ubuntu_clang.sh
  .github/workflows/setup/ubuntu_ompi.sh
Labels: CI

#938 make CI triggers consistent
  .github/workflows/cudaLocal.yml
  .github/workflows/linux.yml
Labels: CI

#942 Fix rocfft 5.5
  docs/source/building/building.rst
  src/fields/fft_poisson_solver/fft/AnyFFT.H
  src/fields/fft_poisson_solver/fft/RocFFTUtils.H
  src/laser/MultiLaser.H
  src/laser/MultiLaser.cpp
Labels: GPU

#943 Option to symmetrize plasma
  docs/source/run/parameters.rst
  src/particles/plasma/PlasmaParticleContainer.H
  src/particles/plasma/PlasmaParticleContainer.cpp
  src/particles/plasma/PlasmaParticleContainerInit.cpp
Labels: component: plasma

#945 Enable 3 MR levels
  docs/source/run/parameters.rst
  src/Hipace.cpp
  src/diagnostics/Diagnostic.cpp
  src/fields/Fields.H
  src/fields/Fields.cpp
  src/particles/beam/BeamParticleContainer.H
  src/particles/beam/BeamParticleContainer.cpp
  src/particles/beam/MultiBeam.H
  src/particles/beam/MultiBeam.cpp
  src/particles/deposition/BeamDepositCurrent.cpp
  src/particles/deposition/ExplicitDeposition.cpp
  src/particles/deposition/PlasmaDepositCurrent.cpp
  src/particles/plasma/MultiPlasma.H
  src/particles/plasma/MultiPlasma.cpp
  src/particles/plasma/PlasmaParticleContainer.H
  src/particles/plasma/PlasmaParticleContainer.cpp
  src/particles/pusher/BeamParticleAdvance.H
  src/particles/pusher/BeamParticleAdvance.cpp
  src/particles/pusher/PlasmaParticleAdvance.cpp
  src/salame/Salame.cpp
  src/utils/AdaptiveTimeStep.cpp
  tests/checksum/benchmarks_json/adaptive_time_step.1Rank.json
Labels: mesh refinement

#946 replace `static` with `inline static` for member variables
  src/Hipace.H
  src/Hipace.cpp
  src/fields/Fields.H
  src/fields/Fields.cpp
  src/utils/Parser.H
Labels: cleaning

#947 Use less than or equal for min_density
  docs/source/run/parameters.rst
  src/particles/plasma/PlasmaParticleContainerInit.cpp
Labels: component: plasma

#949 Don't use tiling in the plasma pusher
  src/Hipace.cpp
  src/particles/plasma/MultiPlasma.cpp
  src/particles/pusher/PlasmaParticleAdvance.H
  src/particles/pusher/PlasmaParticleAdvance.cpp
Labels: component: plasma, cleaning

#955 [mini] Read angularFrequency from mesh instead of from iteration
  src/laser/MultiLaser.cpp
Labels: component: laser envelope

#958 [mini] Fix b0 calculation in collisions
  src/particles/collisions/UpdateMomentumPerez.H
  tests/checksum/benchmarks_json/collisions.SI.1Rank.json
Labels: bug, component: plasma

#951 Implement OMP threading in missing functions
  src/Hipace.cpp
  src/fields/Fields.H
  src/fields/Fields.cpp
  src/fields/fft_poisson_solver/FFTPoissonSolverDirichlet.cpp
  src/fields/fft_poisson_solver/FFTPoissonSolverPeriodic.cpp
  src/fields/fft_poisson_solver/fft/WrapDSTW.cpp
  src/mg_solver/HpMultiGrid.H
  src/mg_solver/HpMultiGrid.cpp
  src/particles/deposition/ExplicitDeposition.cpp
  src/particles/deposition/PlasmaDepositCurrent.cpp
  src/particles/pusher/PlasmaParticleAdvance.cpp
  src/utils/GPUUtil.H
Labels: performance

#948 Gather Ez in loop over slices to gather from proper array
  src/Hipace.cpp
  src/utils/AdaptiveTimeStep.H
  src/utils/AdaptiveTimeStep.cpp
  tests/checksum/benchmarks_json/adaptive_time_step.1Rank.json
  tests/checksum/benchmarks_json/production.SI.2Rank_pwfa.json
Labels: bug, component: beam, Parallelization

#960 [mini] update documentation for Maxwell
  docs/source/building/platforms/maxwell_desy.rst
Labels: documentation

#959 [mini] Fix adaptive time step
  src/utils/AdaptiveTimeStep.H
  src/utils/AdaptiveTimeStep.cpp
  tests/checksum/benchmarks_json/adaptive_time_step.1Rank.json
  tests/checksum/benchmarks_json/production.SI.2Rank_pwfa.json
Labels: bug, component: beam, Parallelization

#961 [mini] Remove unused variables
  src/Hipace.cpp
  src/utils/AdaptiveTimeStep.H
  src/utils/AdaptiveTimeStep.cpp
Labels: cleaning
