Repository Hi-PACE/hipace, pull requests merged in 2023-04, with the labels that each got.

#908 openPMD-api: 0.15.1
  cmake/dependencies/openPMD.cmake
  docs/source/building/building.rst
Labels: component: diagnostics

#898 Multiple diagnostic grids
  docs/source/run/parameters.rst
  examples/beam_in_vacuum/inputs_SI
  examples/beam_in_vacuum/inputs_normalized
  examples/beam_in_vacuum/inputs_normalized_transverse
  examples/blowout_wake/inputs_SI
  examples/blowout_wake/inputs_ionization_SI
  examples/blowout_wake/inputs_normalized
  examples/gaussian_weight/inputs_SI
  examples/gaussian_weight/inputs_normalized
  examples/get_started/inputs_lwfa
  examples/get_started/inputs_normalized
  examples/get_started/inputs_pwfa
  examples/laser/inputs_SI
  examples/linear_wake/inputs_SI
  examples/linear_wake/inputs_ion_motion_SI
  examples/linear_wake/inputs_normalized
  src/Hipace.H
  src/Hipace.cpp
  src/diagnostics/Diagnostic.H
  src/diagnostics/Diagnostic.cpp
  src/diagnostics/OpenPMDWriter.H
  src/diagnostics/OpenPMDWriter.cpp
  src/fields/Fields.H
  src/fields/Fields.cpp
  src/utils/DeprecatedInput.H
  tests/adaptive_time_step.1Rank.sh
  tests/beam_evolution.1Rank.sh
  tests/grid_current.1Rank.sh
  tests/hosing.2Rank.sh
  tests/ionization.2Rank.sh
Labels: component: diagnostics

#900 Reorder plasma for deposition
  docs/source/run/parameters.rst
  src/Hipace.H
  src/Hipace.cpp
  src/particles/plasma/MultiPlasma.H
  src/particles/plasma/MultiPlasma.cpp
  src/particles/plasma/PlasmaParticleContainer.H
  src/particles/plasma/PlasmaParticleContainer.cpp
Labels: component: plasma, GPU, performance

#910 Update doc to point to chat
  README.md
  docs/source/index.rst
  docs/source/run/chat.rst
  docs/source/run/get_started.rst
Labels: documentation

#912 Use parser for beam density
  docs/source/run/parameters.rst
  src/particles/beam/BeamParticleContainer.H
  src/particles/beam/BeamParticleContainer.cpp
  src/particles/profiles/GetInitialDensity.H
  src/particles/profiles/GetInitialDensity.cpp
Labels: component: beam

#911 Remove zeta refinement
  src/Hipace.H
  src/Hipace.cpp
  src/fields/Fields.H
  src/fields/Fields.cpp
Labels: cleaning, mesh refinement

#913 [mini] remove some unused parameters
  src/Hipace.H
  src/Hipace.cpp
  src/diagnostics/OpenPMDWriter.H
  src/diagnostics/OpenPMDWriter.cpp
  src/fields/Fields.H
  src/fields/Fields.cpp
  src/salame/Salame.cpp
Labels: cleaning

#914 add LUMI documentation
  docs/source/building/building.rst
  docs/source/building/platforms/lumi_csc.rst
Labels: documentation

#916 [mini] Add info on n_cell in doc
  docs/source/run/parameters.rst
Labels: documentation

#915 Remove AmrCore
  docs/source/run/parameters.rst
  examples/beam_in_vacuum/inputs_SI
  examples/beam_in_vacuum/inputs_normalized
  examples/beam_in_vacuum/inputs_normalized_transverse
  examples/blowout_wake/inputs_SI
  examples/blowout_wake/inputs_ionization_SI
  examples/blowout_wake/inputs_normalized
  examples/gaussian_weight/inputs_SI
  examples/gaussian_weight/inputs_normalized
  examples/get_started/inputs_lwfa
  examples/get_started/inputs_normalized
  examples/get_started/inputs_pwfa
  examples/laser/inputs_SI
  examples/linear_wake/inputs_SI
  examples/linear_wake/inputs_ion_motion_SI
  examples/linear_wake/inputs_normalized
  src/Hipace.H
  src/Hipace.cpp
  src/diagnostics/Diagnostic.cpp
  src/diagnostics/OpenPMDWriter.H
  src/diagnostics/OpenPMDWriter.cpp
  src/fields/Fields.H
  src/fields/Fields.cpp
  src/particles/beam/BeamParticleContainer.H
  src/particles/beam/BeamParticleContainer.cpp
  src/particles/beam/MultiBeam.H
  src/particles/beam/MultiBeam.cpp
  src/particles/deposition/BeamDepositCurrent.H
  src/particles/deposition/BeamDepositCurrent.cpp
  src/particles/plasma/MultiPlasma.H
  src/particles/plasma/MultiPlasma.cpp
  src/particles/plasma/PlasmaParticleContainer.H
  src/particles/pusher/BeamParticleAdvance.H
  src/particles/pusher/BeamParticleAdvance.cpp
  src/particles/pusher/GetAndSetPosition.H
  src/particles/pusher/GetDomainLev.H
  src/particles/pusher/PlasmaParticleAdvance.cpp
  src/particles/sorting/BoxSort.H
  src/particles/sorting/BoxSort.cpp
  src/particles/sorting/SliceSort.H
  src/particles/sorting/SliceSort.cpp
  src/salame/Salame.H
  src/salame/Salame.cpp
  src/utils/AdaptiveTimeStep.H
  src/utils/AdaptiveTimeStep.cpp
  src/utils/Parser.H
  tests/checksum/benchmarks_json/gaussian_linear_wake.SI.1Rank.json
  tests/checksum/benchmarks_json/linear_wake.SI.1Rank.json
  tests/gaussian_linear_wake.SI.1Rank.sh
  tests/linear_wake.SI.1Rank.sh
Labels: cleaning, mesh refinement

#921 Support new AMReX particle interfaces
  src/particles/beam/BeamParticleContainer.H
  src/particles/plasma/PlasmaParticleContainer.H
  src/particles/sorting/BoxSort.cpp
Labels: bug

#922 remove /usr/local from brew cache
  .github/workflows/macos.yml
  src/Hipace.H
Labels: performance, CI

#920 Interpolate current to level 1
  src/Hipace.cpp
  src/fields/Fields.cpp
Labels: mesh refinement

#925 Update LUMI doc
  docs/source/building/platforms/lumi_csc.rst
Labels: bug, documentation
