Repository Hi-PACE/hipace, pull requests merged in 2023-11, with the labels that each got.

#1021 Add interpolate_neutralizing_background option
  docs/source/run/parameters.rst
  src/Hipace.H
  src/Hipace.cpp
Labels: component: plasma, mesh refinement

#1026 Add option to limit number of buffered beam slices
  docs/source/run/parameters.rst
  src/Hipace.H
  src/Hipace.cpp
  src/utils/MultiBuffer.H
  src/utils/MultiBuffer.cpp
Labels: component: beam, Parallelization

#1028 Beam external field from parser
  docs/source/run/parameters.rst
  examples/beam_in_vacuum/inputs_RR
  src/Hipace.H
  src/Hipace.cpp
  src/particles/beam/BeamParticleContainer.H
  src/particles/beam/BeamParticleContainer.cpp
  src/particles/beam/MultiBeam.H
  src/particles/beam/MultiBeam.cpp
  src/particles/pusher/BeamParticleAdvance.H
  src/particles/pusher/BeamParticleAdvance.cpp
  src/particles/pusher/ExternalFields.H
  tests/adaptive_time_step.1Rank.sh
  tests/beam_evolution.1Rank.sh
Labels: component: beam

#1031 Fix External AMReX Builds
  cmake/dependencies/AMReX.cmake
Labels: bug

#1033 Update amrex version when checking for pre-installed version
  cmake/dependencies/AMReX.cmake
Labels: build

#1034 Update version numbers before release
  CMakeLists.txt
  cmake/dependencies/AMReX.cmake
  docs/source/conf.py
  license.txt
Labels: documentation, build

#1035 Hipace dev builds on amrex dev
  cmake/dependencies/AMReX.cmake
Labels: build

#1039 Doc: Button to Copy Code Blocks
  docs/requirements.txt
  docs/source/conf.py
Labels: documentation

#1036 [mini] Fix typo in laser pulse length to pulse duration conversion
  docs/source/run/parameters.rst
  src/laser/Laser.cpp
Labels: bug, documentation, component: laser envelope, non-backward-compatible

#1041 Fix typo in assert
  src/Hipace.cpp
Labels: bug, Parallelization

#1038 Add option to symmetrize fields
  docs/source/run/parameters.rst
  src/Hipace.cpp
  src/fields/Fields.H
  src/fields/Fields.cpp
Labels: component: fields

#1043 Laser FFT solver for AMD
  src/laser/MultiLaser.H
  src/laser/MultiLaser.cpp
Labels: GPU, component: laser envelope

#1044 Set `amrex.omp_threads = "nosmt"`
  docs/source/run/parameters.rst
  src/utils/Parser.H
Labels: performance
