Repository Hi-PACE/hipace, pull requests merged in 2023-12, with the labels that each got.

#1047 Use 64 bit idcpu
  src/diagnostics/OpenPMDWriter.H
  src/diagnostics/OpenPMDWriter.cpp
  src/particles/beam/BeamParticleContainer.H
  src/particles/beam/BeamParticleContainer.cpp
  src/particles/beam/BeamParticleContainerInit.cpp
  src/particles/plasma/PlasmaParticleContainer.H
  src/particles/plasma/PlasmaParticleContainer.cpp
  src/particles/plasma/PlasmaParticleContainerInit.cpp
  src/particles/sorting/SliceSort.cpp
  src/salame/Salame.cpp
  src/utils/AdaptiveTimeStep.cpp
  src/utils/MultiBuffer.H
  src/utils/MultiBuffer.cpp
Labels: bug

#1048 CI: Fix ROCm 6.0 `hiprand`
  .github/workflows/setup/hip.sh
Labels: CI

#1050 Fix minor formatting issue in documentation
  docs/source/run/parameters.rst
Labels: component: diagnostics

#1051 Make plasma ppc a mandatory input parameter
  docs/source/run/parameters.rst
  src/particles/plasma/PlasmaParticleContainer.cpp
Labels: component: plasma, cleaning

#1049 MacOS CI explicitly install python@3.12
  .github/workflows/macos.yml
Labels: CI

#1002 Laser with non-electron plasma
  src/Hipace.cpp
  src/particles/deposition/ExplicitDeposition.cpp
  src/particles/deposition/PlasmaDepositCurrent.cpp
  src/particles/pusher/PlasmaParticleAdvance.cpp
  src/particles/pusher/PushPlasmaParticles.H
Labels: component: laser envelope
