Repository Hi-PACE/hipace, pull requests merged in 2023-03, with the labels that each got.

#866 Read in Laser form OpenPMD file
  docs/source/run/parameters.rst
  src/laser/Laser.H
  src/laser/Laser.cpp
  src/laser/MultiLaser.H
  src/laser/MultiLaser.cpp
Labels: component: laser envelope

#870 Output normalized momentum instead of proper velocity in insitu diagnostics
  src/particles/beam/BeamParticleContainer.cpp
Labels: component: beam, component: diagnostics

#874 CI: macOS
  .github/workflows/macos.yml
Labels: CI

#873 CI: Windows
  .github/workflows/windows.yml
  CMakeLists.txt
  src/utils/Parser.H
Labels: bug, CI

#867 Use only one MultiFab for all laser slices
  src/Hipace.cpp
  src/fields/Fields.cpp
  src/laser/MultiLaser.H
  src/laser/MultiLaser.cpp
  src/particles/deposition/ExplicitDeposition.cpp
  src/particles/deposition/PlasmaDepositCurrent.cpp
  src/particles/pusher/PlasmaParticleAdvance.cpp
Labels: cleaning, component: laser envelope

#880 Update release number and fix dependency
  CMakeLists.txt
  cmake/dependencies/AMReX.cmake
  docs/source/conf.py
  license.txt
Labels: documentation, build

#881 CI: macOS Only One
  .github/workflows/macos.yml
Labels: performance, CI

#871 Allow for arbitrary sized diagnostics grid
  docs/source/run/parameters.rst
  examples/blowout_wake/analysis_slice_IO.py
  src/diagnostics/Diagnostic.H
  src/diagnostics/Diagnostic.cpp
  src/diagnostics/OpenPMDWriter.H
  src/diagnostics/OpenPMDWriter.cpp
  tests/slice_IO.1Rank.sh
Labels: component: diagnostics

#885 Reduce memory footprint of plasma initialization
  src/laser/MultiLaser.H
  src/laser/MultiLaser.cpp
  src/particles/plasma/PlasmaParticleContainerInit.cpp
Labels: component: plasma

#888 [mini] Print pusher for which HiPACE++ was compiled
  cmake/HiPACEFunctions.cmake
Labels: build

#886 [mini] When a checksum test fails, also print the whole new json file
  tests/checksum/checksum.py
Labels: CI

#889 [mini] Remove unused variable in adaptive time step
  src/utils/AdaptiveTimeStep.cpp
Labels: cleaning, build, Parallelization

#890 [mini] rename to avoid compiler warning
  src/utils/AdaptiveTimeStep.cpp
Labels: cleaning, build

#892 [mini] fix print statement for small DSTs using rocFFT
  src/fields/fft_poisson_solver/fft/WrapRocDST.cpp
Labels: cleaning

#887 CI on GPU
  .github/workflows/local_gpu.yml
  CMakeLists.txt
Labels: GPU, performance, CI

#905 [mini] Better print statement when checksum fails
  tests/checksum/checksum.py
Labels: CI
