Repository Hi-PACE/hipace, pull requests merged in 2024-04, with the labels that each got.

#1085 Limit size in GiB of communications buffer
  docs/source/run/parameters.rst
  src/Hipace.cpp
  src/utils/MultiBuffer.H
  src/utils/MultiBuffer.cpp
Labels: performance, Parallelization

#1089 NVCC 11.5 fixes
  src/fields/Fields.cpp
  src/laser/MultiLaser.cpp
  src/particles/beam/BeamParticleContainer.cpp
  src/particles/plasma/PlasmaParticleContainer.cpp
Labels: bug

#1090 Use 63 bits for Beam ID
  docs/source/run/parameters.rst
  src/diagnostics/OpenPMDWriter.cpp
  src/particles/beam/BeamParticleContainer.H
  src/particles/beam/BeamParticleContainer.cpp
  src/particles/beam/BeamParticleContainerInit.cpp
  src/particles/deposition/BeamDepositCurrent.cpp
  src/particles/plasma/PlasmaParticleContainer.cpp
  src/particles/plasma/PlasmaParticleContainerInit.cpp
  tests/checksum/benchmarks_json/production.SI.2Rank_pwfa.json
Labels: component: beam, component: diagnostics

#1091 correct the direction of the spatial rotation
  src/laser/MultiLaser.cpp
Labels: bug, component: laser envelope

#1088 Put Laser abs(a) in separate Field
  src/Hipace.cpp
  src/fields/Fields.cpp
  src/laser/MultiLaser.H
  src/laser/MultiLaser.cpp
  src/particles/deposition/ExplicitDeposition.H
  src/particles/deposition/ExplicitDeposition.cpp
  src/particles/deposition/PlasmaDepositCurrent.H
  src/particles/deposition/PlasmaDepositCurrent.cpp
  src/particles/particles_utils/FieldGather.H
  src/particles/plasma/MultiPlasma.H
  src/particles/plasma/MultiPlasma.cpp
  src/particles/pusher/PlasmaParticleAdvance.H
  src/particles/pusher/PlasmaParticleAdvance.cpp
  src/salame/Salame.cpp
  src/utils/GPUUtil.H
  tests/checksum/benchmarks_json/laser_blowout_wake_explicit.1Rank.json
  tests/checksum/benchmarks_json/laser_blowout_wake_explicit.SI.1Rank.json
  tests/checksum/benchmarks_json/laser_evolution.SI.2Rank.json
  tests/checksum/benchmarks_json/production.SI.2Rank_lwfa.json
Labels: component: laser envelope

#1087 Clean-up TinyProfiler output
  docs/source/run/parameters.rst
  src/Hipace.H
  src/Hipace.cpp
  src/diagnostics/Diagnostic.cpp
  src/fields/Fields.H
  src/fields/Fields.cpp
  src/fields/fft_poisson_solver/FFTPoissonSolverDirichlet.cpp
  src/fields/fft_poisson_solver/FFTPoissonSolverPeriodic.cpp
  src/fields/fft_poisson_solver/MGPoissonSolverDirichlet.cpp
  src/fields/fft_poisson_solver/fft/AnyDST.H
  src/fields/fft_poisson_solver/fft/WrapCuDST.cpp
  src/fields/fft_poisson_solver/fft/WrapCuFFT.cpp
  src/fields/fft_poisson_solver/fft/WrapDSTW.cpp
  src/fields/fft_poisson_solver/fft/WrapFFTW.cpp
  src/fields/fft_poisson_solver/fft/WrapRocDST.cpp
  src/fields/fft_poisson_solver/fft/WrapRocFFT.cpp
  src/particles/beam/BeamParticleContainer.cpp
  src/particles/plasma/MultiPlasma.cpp
  src/particles/plasma/PlasmaParticleContainer.cpp
  src/particles/plasma/PlasmaParticleContainerInit.cpp
  src/particles/sorting/SliceSort.cpp
  src/utils/GridCurrent.cpp
  src/utils/HipaceProfilerWrapper.H
  src/utils/MultiBuffer.cpp
Labels: cleaning

#1094 Fix Spin in-situ diagnostic for NVCC 11.5
  src/particles/beam/BeamParticleContainer.cpp
Labels: bug

#1093 Simplify tiling in plasma deposition
  docs/source/run/parameters.rst
  src/Hipace.cpp
  src/fields/Fields.H
  src/fields/Fields.cpp
  src/particles/deposition/PlasmaDepositCurrent.cpp
  src/utils/Parser.H
Labels: component: plasma, cleaning, performance

#1096 Fix Plasma tiling in SALAME
  src/salame/Salame.cpp
Labels: bug

#1097 Fix SALAME overloaded beam removal
  src/salame/Salame.cpp
Labels: bug

#1095 Don't use Laser FFT array in Laser MG solver
  src/laser/MultiLaser.cpp
Labels: cleaning, component: laser envelope

#1102 Fix index bug in FFTPoissonSolverPeriodic
  src/fields/fft_poisson_solver/FFTPoissonSolverPeriodic.cpp
Labels: bug

#1092 Fix adaptive time step for non-electron beams
  src/particles/plasma/MultiPlasma.H
  src/particles/plasma/MultiPlasma.cpp
  src/utils/AdaptiveTimeStep.H
  src/utils/AdaptiveTimeStep.cpp
Labels: bug, component: beam
