Repository Hi-PACE/hipace, pull requests merged in 2024-07, with the labels that each got.

#1122 Read laser profile from parser
  docs/source/run/parameters.rst
  src/laser/Laser.H
  src/laser/Laser.cpp
  src/laser/MultiLaser.cpp
Labels: component: laser envelope

#1126 Clean in-situ diagnostic with TupleSplit and tupleToArray
  src/fields/Fields.cpp
  src/laser/MultiLaser.cpp
  src/particles/beam/BeamParticleContainer.cpp
  src/particles/plasma/PlasmaParticleContainer.cpp
Labels: cleaning

#1127 Remove `amrex::Gpu::notInLaunchRegion()` checks
  src/Hipace.cpp
  src/fields/Fields.H
  src/fields/Fields.cpp
  src/fields/fft_poisson_solver/FFTPoissonSolverDirichletDirect.cpp
  src/fields/fft_poisson_solver/FFTPoissonSolverPeriodic.cpp
  src/laser/MultiLaser.cpp
  src/particles/deposition/ExplicitDeposition.cpp
  src/particles/pusher/PlasmaParticleAdvance.cpp
  src/salame/Salame.cpp
Labels: cleaning

#1132 Fix compilation without openpmd
  src/laser/MultiLaser.cpp
  src/particles/beam/BeamParticleContainerInit.cpp
  src/utils/IOUtil.cpp
Labels: bug

#1133 Add fix for slow GPU aware MPI to JSC booster script
  docs/source/building/platforms/booster_jsc.rst
Labels: documentation, GPU, performance, Parallelization

#1134 Add pre_register_memory option
  docs/source/run/parameters.rst
  src/utils/MultiBuffer.H
  src/utils/MultiBuffer.cpp
Labels: performance, Parallelization

#1138 Fix unused parameter warning
  src/laser/Laser.H
  src/laser/Laser.cpp
  src/laser/MultiLaser.cpp
Labels: component: laser envelope

#1142 Remove particles with negative psi_inv
  src/particles/deposition/PlasmaDepositCurrent.cpp
Labels: bug

#1137 HPMG: Compute finest level directly on the field
  src/Hipace.cpp
  src/laser/MultiLaser.H
  src/laser/MultiLaser.cpp
  src/mg_solver/HpMultiGrid.H
  src/mg_solver/HpMultiGrid.cpp
  tests/beam_in_vacuum.SI.1Rank.sh
  tests/beam_in_vacuum.normalized.1Rank.sh
  tests/checksum/benchmarks_json/adaptive_time_step.1Rank.json
  tests/checksum/benchmarks_json/beam_evolution.1Rank.json
  tests/checksum/benchmarks_json/beam_in_vacuum.SI.1Rank.json
  tests/checksum/benchmarks_json/beam_in_vacuum.SI.Serial.json
  tests/checksum/benchmarks_json/beam_in_vacuum.normalized.1Rank.json
  tests/checksum/benchmarks_json/beam_in_vacuum.normalized.Serial.json
  tests/checksum/benchmarks_json/blowout_wake.2Rank.json
  tests/checksum/benchmarks_json/blowout_wake_explicit.2Rank.json
  tests/checksum/benchmarks_json/collisions.SI.1Rank.json
  tests/checksum/benchmarks_json/collisions_beam.SI.1Rank.json
  tests/checksum/benchmarks_json/gaussian_linear_wake.SI.1Rank.json
  tests/checksum/benchmarks_json/gaussian_linear_wake.normalized.1Rank.json
  tests/checksum/benchmarks_json/grid_current.1Rank.json
  tests/checksum/benchmarks_json/ion_motion.SI.1Rank.json
  tests/checksum/benchmarks_json/ionization.2Rank.json
  tests/checksum/benchmarks_json/laser_blowout_wake_explicit.1Rank.json
  tests/checksum/benchmarks_json/laser_blowout_wake_explicit.SI.1Rank.json
  tests/checksum/benchmarks_json/linear_wake.SI.1Rank.json
  tests/checksum/benchmarks_json/linear_wake.normalized.1Rank.json
  tests/checksum/benchmarks_json/production.SI.2Rank_lwfa.json
  tests/checksum/benchmarks_json/production.SI.2Rank_pwfa.json
  tests/checksum/benchmarks_json/radiation_reaction.1Rank.json
  tests/checksum/benchmarks_json/reset.2Rank.json
  tests/checksum/benchmarks_json/transverse_benchmark.1Rank.json
  tests/reset.2Rank.sh
Labels: component: fields, performance
