Repository Hi-PACE/hipace, pull requests merged in 2024-03, with the labels that each got.

#1078 [mini] Revert amrex branch to build hipace-dev on amrex-dev
  cmake/dependencies/AMReX.cmake
Labels: build

#1076 Improve Maxwell documentation to setup and run
  docs/source/building/platforms/maxwell_desy.rst
Labels: documentation, build

#1063 Add option to use HPMG to solve Poisson equations
  docs/source/run/parameters.rst
  src/Hipace.cpp
  src/fields/Fields.H
  src/fields/Fields.cpp
  src/fields/fft_poisson_solver/CMakeLists.txt
  src/fields/fft_poisson_solver/FFTPoissonSolver.H
  src/fields/fft_poisson_solver/FFTPoissonSolverDirichlet.H
  src/fields/fft_poisson_solver/FFTPoissonSolverDirichlet.cpp
  src/fields/fft_poisson_solver/FFTPoissonSolverPeriodic.H
  src/fields/fft_poisson_solver/FFTPoissonSolverPeriodic.cpp
  src/fields/fft_poisson_solver/MGPoissonSolverDirichlet.H
  src/fields/fft_poisson_solver/MGPoissonSolverDirichlet.cpp
  src/laser/MultiLaser.cpp
  src/mg_solver/HpMultiGrid.H
  src/mg_solver/HpMultiGrid.cpp
Labels: component: fields

#1079 Fix MPI buffer max_leading_slices
  docs/source/run/parameters.rst
  src/Hipace.cpp
  src/utils/MultiBuffer.cpp
Labels: bug, Parallelization

#1071 Add Beam Spin tracking
  docs/source/run/parameters.rst
  src/diagnostics/OpenPMDWriter.cpp
  src/particles/beam/BeamParticleContainer.H
  src/particles/beam/BeamParticleContainer.cpp
  src/particles/pusher/BeamParticleAdvance.cpp
Labels: component: beam

#1080 Put input parameters for MPI in a separate category
  docs/source/building/platforms/booster_jsc.rst
  docs/source/building/platforms/lumi_csc.rst
  docs/source/building/platforms/maxwell_desy.rst
  docs/source/building/platforms/perlmutter_nersc.rst
  docs/source/run/parameters.rst
  src/Hipace.H
  src/Hipace.cpp
  src/laser/MultiLaser.cpp
  src/utils/MultiBuffer.H
  src/utils/MultiBuffer.cpp
Labels: cleaning, Parallelization, non-backward-compatible

#1081 Reverse order of MPI ranks
  src/Hipace.H
  src/Hipace.cpp
  src/laser/MultiLaser.cpp
  src/particles/beam/BeamParticleContainer.cpp
  src/utils/AdaptiveTimeStep.cpp
  src/utils/IOUtil.H
  src/utils/IOUtil.cpp
  src/utils/MultiBuffer.cpp
  tests/checksum/benchmarks_json/ionization.2Rank.json
  tests/checksum/benchmarks_json/production.SI.2Rank_pwfa.json
Labels: cleaning, Parallelization

#1084 [mini] Add doc entry for use_previous_rng
  docs/source/run/parameters.rst
Labels: documentation, non-backward-compatible

#1082 Make CPU-GPU memory copy highly asynchronous
  docs/source/run/parameters.rst
  src/utils/MultiBuffer.H
  src/utils/MultiBuffer.cpp
Labels: GPU, performance, Parallelization

#1086 Add in-situ diagnostic for spin
  docs/source/run/parameters.rst
  src/particles/beam/BeamParticleContainer.H
  src/particles/beam/BeamParticleContainer.cpp
  src/utils/InsituUtil.H
Labels: component: beam, component: diagnostics
