Repository Hi-PACE/hipace, pull requests merged in 2024-02, with the labels that each got.

#1065 Add HiPACE_CCACHE Option
  CMakeLists.txt
Labels: build

#1058 Add [x*uy], [y*ux], [ux/uz], [uy/uz] to beam in-situ diagnostics
  docs/source/run/parameters.rst
  src/fields/Fields.H
  src/fields/Fields.cpp
  src/particles/beam/BeamParticleContainer.H
  src/particles/beam/BeamParticleContainer.cpp
Labels: component: beam, component: diagnostics

#1060 Add laser insitu diagnostics
  docs/source/run/parameters.rst
  src/Hipace.cpp
  src/fields/Fields.cpp
  src/laser/MultiLaser.H
  src/laser/MultiLaser.cpp
  src/utils/InsituUtil.H
Labels: component: diagnostics, component: laser envelope

#1067 Use amre::removeInvalidParticles for the Beam
  src/particles/sorting/SliceSort.cpp
Labels: cleaning

#1062 Fix hpmg for some non-ideal resolutions
  src/mg_solver/HpMultiGrid.H
  src/mg_solver/HpMultiGrid.cpp
Labels: bug

#1073 Try fix MacOS CI by unlinking Python
  .github/workflows/macos.yml
Labels: bug, CI

#1068 Prepare Beam Communication for Runtime Components
  src/particles/beam/BeamParticleContainer.H
  src/particles/beam/BeamParticleContainer.cpp
  src/utils/MultiBuffer.H
  src/utils/MultiBuffer.cpp
Labels: component: beam, Parallelization

#1069 Add support for Spin to openPMD Beam output
  src/diagnostics/OpenPMDWriter.H
  src/diagnostics/OpenPMDWriter.cpp
  src/particles/beam/BeamParticleContainer.H
  src/utils/IOUtil.cpp
Labels: component: beam, component: diagnostics

#1070 Use amre::GpuComplex in diagnostics
  src/diagnostics/Diagnostic.H
Labels: cleaning

#1074 [mini] Option to specify laser CEP
  src/laser/Laser.H
  src/laser/Laser.cpp
  src/laser/MultiLaser.cpp
Labels: component: laser envelope

#1075 [mini] Fix typos in executable names in doc
  docs/source/building/platforms/booster_jsc.rst
  docs/source/building/platforms/spock_olcf.rst
Labels: documentation
