Repository Hi-PACE/hipace, pull requests merged in 2024-09, with the labels that each got.

#1156 [mini] Fix outdated documentation points
  README.md
  docs/source/index.rst
Labels: documentation

#1064 Fix boundary conditions
  docs/source/run/parameters.rst
  examples/beam_in_vacuum/inputs_RR
  examples/beam_in_vacuum/inputs_SI
  examples/beam_in_vacuum/inputs_normalized
  examples/beam_in_vacuum/inputs_normalized_transverse
  examples/benchmarks/inputs_timestep_benchmark
  examples/benchmarks/inputs_transverse_benchmark
  examples/blowout_wake/inputs_SI
  examples/blowout_wake/inputs_ionization_SI
  examples/blowout_wake/inputs_normalized
  examples/gaussian_weight/inputs_SI
  examples/gaussian_weight/inputs_normalized
  examples/get_started/inputs_lwfa
  examples/get_started/inputs_normalized
  examples/get_started/inputs_pwfa
  examples/laser/inputs_SI
  examples/linear_wake/inputs_SI
  examples/linear_wake/inputs_ion_motion_SI
  examples/linear_wake/inputs_normalized
  src/Hipace.H
  src/Hipace.cpp
  src/diagnostics/Diagnostic.cpp
  src/fields/Fields.H
  src/fields/Fields.cpp
  src/fields/fft_poisson_solver/FFTPoissonSolver.H
  src/fields/fft_poisson_solver/FFTPoissonSolverDirichletDirect.cpp
  src/fields/fft_poisson_solver/FFTPoissonSolverDirichletExpanded.cpp
  src/fields/fft_poisson_solver/FFTPoissonSolverDirichletFast.cpp
  src/fields/fft_poisson_solver/FFTPoissonSolverPeriodic.cpp
  src/fields/fft_poisson_solver/MGPoissonSolverDirichlet.cpp
  src/particles/beam/BeamParticleContainer.cpp
  src/particles/beam/BeamParticleContainerInit.cpp
  src/particles/plasma/MultiPlasma.cpp
  src/particles/plasma/PlasmaParticleContainer.H
  src/particles/plasma/PlasmaParticleContainer.cpp
  src/particles/plasma/PlasmaParticleContainerInit.cpp
  src/particles/pusher/BeamParticleAdvance.cpp
  src/particles/pusher/GetAndSetPosition.H
  src/particles/pusher/PlasmaParticleAdvance.cpp
  tests/beam_in_vacuum_open_boundary.normalized.1Rank.sh
  tests/checksum/benchmarks_json/beam_in_vacuum_open_boundary.normalized.1Rank.json
  tests/checksum/benchmarks_json/blowout_wake.2Rank.json
  tests/checksum/benchmarks_json/blowout_wake_explicit.2Rank.json
  tests/checksum/benchmarks_json/collisions.SI.1Rank.json
  tests/checksum/benchmarks_json/collisions_beam.SI.1Rank.json
  tests/checksum/benchmarks_json/gaussian_linear_wake.SI.1Rank.json
  tests/checksum/benchmarks_json/gaussian_linear_wake.normalized.1Rank.json
  tests/checksum/benchmarks_json/ion_motion.SI.1Rank.json
  tests/checksum/benchmarks_json/ionization.2Rank.json
  tests/checksum/benchmarks_json/laser_blowout_wake_explicit.1Rank.json
  tests/checksum/benchmarks_json/laser_blowout_wake_explicit.SI.1Rank.json
  tests/checksum/benchmarks_json/linear_wake.SI.1Rank.json
  tests/checksum/benchmarks_json/linear_wake.normalized.1Rank.json
  tests/checksum/benchmarks_json/production.SI.2Rank_lwfa.json
  tests/checksum/benchmarks_json/production.SI.2Rank_pwfa.json
  tests/checksum/benchmarks_json/reset.2Rank.json
  tests/checksum/benchmarks_json/transverse_benchmark.1Rank.json
Labels: bug, component: plasma, component: beam, component: fields, non-backward-compatible

#1152 CMake: Replace `FetchContent_Populate`
  CMakeLists.txt
  cmake/dependencies/AMReX.cmake
  cmake/dependencies/openPMD.cmake
  docs/source/building/building.rst
  docs/source/building/platforms/perlmutter_nersc.rst
Labels: build

#1155 Doc: Spock (OLCF) Gone
  docs/source/building/hpc.rst
  docs/source/building/platforms/spock_olcf.rst
Labels: documentation, cleaning

#1159 Reset std::setfill in format_time
  src/utils/IOUtil.cpp
Labels: bug

#1162 Add nanoseconds per particle push printout
  src/Hipace.H
  src/Hipace.cpp
  src/laser/MultiLaser.cpp
  src/particles/pusher/BeamParticleAdvance.cpp
  src/particles/pusher/PlasmaParticleAdvance.cpp
Labels: performance

#1163 Fix float assert in Parser
  src/utils/Parser.H
Labels: bug

#1167 Fix HPMG cuda graph with SALAME
  src/mg_solver/HpMultiGrid.H
  src/mg_solver/HpMultiGrid.cpp
Labels: bug

#1148 Fix max_time with negative dt
  src/Hipace.H
  src/Hipace.cpp
Labels: bug

#1168 Update Lumi modules
  docs/source/building/platforms/lumi_csc.rst
Labels: documentation, build

#1171 Add rhomjz_beam field
  src/fields/Fields.cpp
Labels: bug
