Repository Hi-PACE/hipace, pull requests merged in 2024-10, with the labels that each got.

#1158 Shared memory deposition
  docs/source/run/parameters.rst
  examples/linear_wake/inputs_ion_motion_SI
  src/Hipace.H
  src/Hipace.cpp
  src/particles/deposition/BeamDepositCurrent.cpp
  src/particles/deposition/DepositionUtil.H
  src/particles/deposition/ExplicitDeposition.cpp
  src/particles/deposition/PlasmaDepositCurrent.H
  src/particles/deposition/PlasmaDepositCurrent.cpp
  src/particles/plasma/MultiPlasma.H
  src/particles/plasma/MultiPlasma.cpp
  src/particles/pusher/PlasmaParticleAdvance.H
  src/salame/Salame.cpp
  src/utils/GPUUtil.H
  tests/adaptive_time_step.1Rank.sh
  tests/beam_evolution.1Rank.sh
  tests/beam_in_vacuum.SI.1Rank.sh
  tests/beam_in_vacuum.SI.Serial.sh
  tests/beam_in_vacuum.normalized.1Rank.sh
  tests/beam_in_vacuum.normalized.2Rank.sh
  tests/beam_in_vacuum.normalized.Serial.sh
  tests/beam_in_vacuum_open_boundary.normalized.1Rank.sh
  tests/blowout_wake.2Rank.sh
  tests/blowout_wake.Serial.sh
  tests/blowout_wake_explicit.2Rank.sh
  tests/from_file.SI.1Rank.sh
  tests/from_file.normalized.1Rank.sh
  tests/gaussian_linear_wake.SI.1Rank.sh
  tests/gaussian_linear_wake.normalized.1Rank.sh
  tests/gaussian_weight.1Rank.sh
  tests/grid_current.1Rank.sh
  tests/hosing.2Rank.sh
  tests/ionization.2Rank.sh
  tests/laser_blowout_wake_explicit.1Rank.sh
  tests/laser_blowout_wake_explicit.SI.1Rank.sh
  tests/linear_wake.SI.1Rank.sh
  tests/linear_wake.normalized.1Rank.sh
  tests/next_deposition_beam.2Rank.sh
  tests/output_coarsening.2Rank.sh
  tests/reset.2Rank.sh
  tests/restart.normalized.1Rank.sh
  tests/slice_IO.1Rank.sh
Labels: component: plasma, component: beam, GPU, performance

#1160 Faster multigrid solve with OMP
  src/mg_solver/HpMultiGrid.cpp
Labels: component: fields, performance

#1161 OMP parallelize Beam pusher
  src/particles/pusher/BeamParticleAdvance.cpp
  src/particles/pusher/PlasmaParticleAdvance.cpp
  src/utils/OMPUtil.H
Labels: component: plasma, component: beam, cleaning, performance

#1176 openPMD-api: 0.16.0+
  cmake/dependencies/openPMD.cmake
  docs/source/building/building.rst
Labels: component: diagnostics

#1179 [mini] Forgot to bump checkout version in 1 place
  .github/workflows/cuda.yml
Labels: CI

#1183 Use amrex::GpuArray instead of std::array in deposition
  src/particles/deposition/BeamDepositCurrent.cpp
  src/particles/deposition/DepositionUtil.H
  src/particles/deposition/ExplicitDeposition.cpp
  src/particles/deposition/PlasmaDepositCurrent.cpp
Labels: bug
