Repository Hi-PACE/hipace, pull requests merged in 2024-06, with the labels that each got.

#1111 Improve performance of FFTDirichletExpanded
  src/fields/fft_poisson_solver/FFTPoissonSolverDirichletExpanded.H
  src/fields/fft_poisson_solver/FFTPoissonSolverDirichletExpanded.cpp
Labels: performance

#1112 Improve performance of FFTDirichletFast
  src/fields/fft_poisson_solver/FFTPoissonSolverDirichletFast.H
  src/fields/fft_poisson_solver/FFTPoissonSolverDirichletFast.cpp
  src/utils/GPUUtil.H
Labels: performance

#1125 Add a relative tolerance to SALAME
  docs/source/run/parameters.rst
  src/Hipace.H
  src/Hipace.cpp
  src/salame/Salame.H
  src/salame/Salame.cpp
Labels: component: beam, component: fields

#1128 Add inputs for scaling benchmarks to examples
  CMakeLists.txt
  examples/benchmarks/inputs_timestep_benchmark
  examples/benchmarks/inputs_transverse_benchmark
  tests/checksum/benchmarks_json/transverse_benchmark.1Rank.json
  tests/checksum/reset_all_benchmarks.sh
  tests/transverse_benchmark.1Rank.sh
Labels: performance, CI

#1129 CI: CCache for macOS
  .github/workflows/macos.yml
Labels: CI
