Repository Hi-PACE/hipace, pull requests merged in 2024-05, with the labels that each got.

#1101 Remove outer_depos_loop
  docs/source/run/parameters.rst
  src/Hipace.H
  src/Hipace.cpp
  src/particles/deposition/PlasmaDepositCurrent.cpp
  src/particles/plasma/PlasmaParticleContainer.cpp
  src/particles/plasma/PlasmaParticleContainerInit.cpp
  tests/blowout_wake.2Rank.sh
  tests/blowout_wake_explicit.2Rank.sh
Labels: cleaning

#1103 Use correct geometry for Laser diagnostics
  src/fields/Fields.cpp
  src/laser/MultiLaser.H
Labels: bug, component: diagnostics, component: laser envelope, mesh refinement

#1104 Fix ReorderParticles for Beam
  src/particles/beam/BeamParticleContainer.cpp
Labels: bug, component: beam

#1107 Sort plasma after initialization when running on CPU
  src/particles/plasma/PlasmaParticleContainerInit.cpp
Labels: component: plasma, performance

#1113 CI: Update ROCm/HIP
  .github/workflows/setup/hip.sh
Labels: CI

#1115 Doc: Fix Legal References
  README.md
Labels: bug, documentation

#1118 CMake: No Deprecation Warnings
  CMakeLists.txt
Labels: build

#1106 Separate grid for Laser
  docs/source/run/parameters.rst
  src/Hipace.H
  src/Hipace.cpp
  src/diagnostics/Diagnostic.H
  src/diagnostics/Diagnostic.cpp
  src/diagnostics/OpenPMDWriter.cpp
  src/fields/Fields.H
  src/fields/Fields.cpp
  src/laser/MultiLaser.H
  src/laser/MultiLaser.cpp
  src/utils/MultiBuffer.H
  src/utils/MultiBuffer.cpp
Labels: component: laser envelope, non-backward-compatible

#1108 Fix tiling without OMP
  src/Hipace.H
  src/particles/deposition/PlasmaDepositCurrent.cpp
Labels: bug

#1114 Amend Notices for Non-Endorsement
  legal.txt
Labels: documentation

#1117 Initialize MR level with beam from file
  src/particles/beam/BeamParticleContainer.cpp
Labels: bug, component: beam

#1119 Use less than or equal for min_density with beam
  docs/source/run/parameters.rst
  src/particles/beam/BeamParticleContainerInit.cpp
Labels: component: beam

#1121 Fix openPMD crash if beam has no particles
  src/diagnostics/OpenPMDWriter.cpp
Labels: bug, component: beam
