Repository Hi-PACE/hipace, pull requests merged in 2025-02, with the labels that each got.

#1199 Re-enable warnings as errors in doxygen CI
  .github/workflows/source/buildDoxygen
Labels: CI

#1204 Fix issue with AB5 pusher and MR
  src/Hipace.cpp
  src/particles/plasma/MultiPlasma.H
  src/particles/plasma/MultiPlasma.cpp
  src/particles/pusher/PlasmaParticleAdvance.H
  src/particles/pusher/PlasmaParticleAdvance.cpp
  src/salame/Salame.cpp
Labels: bug, component: plasma

#1200 Remove invalid beam particle from first diagnostic step
  src/particles/beam/BeamParticleContainer.cpp
  src/particles/beam/BeamParticleContainerInit.cpp
  src/salame/Salame.cpp
Labels: bug, component: beam

#1203 New option to disable the pusher for plasma particles
  docs/source/run/parameters.rst
  src/particles/plasma/MultiPlasma.cpp
  src/particles/plasma/PlasmaParticleContainer.H
  src/particles/plasma/PlasmaParticleContainer.cpp
Labels: documentation, component: plasma

#1205 RTD: Fix GA Integration
  docs/requirements.txt
  docs/source/conf.py
Labels: bug, documentation

#1208 Remove conda from CI
  .github/workflows/source.yml
Labels: bug, CI

#1209 Fix unused variable warning
  src/particles/pusher/PlasmaParticleAdvance.cpp
Labels: cleaning
